const tracery = require("tracery-grammar");

const grammar = tracery.createGrammar({
  short: [
    "Mom's a mood swinger.",
    "In between swinging, Mom did housework.",
    "Part of an heirloom chandelier crashed to the ground.",
    "She swung on top of the bed in my younger Sister's room.",
    "But this was something I confirmed after I had my own swing.",
    "What exactly happened out there?",
    "At some point, I remember yanking on her arm, asking, Why swing?",
    "Swimming builds bulky shoulders and chlorine turns hair green.",
    "I swallowed my pride and listened to Mom: Give yourself time.",
    "She'd shake her head, call after the ball, Dingbat!",
    "Dad didn't mind.",
    "Just to get the ball closer to the hole.",
    "Dad's the original swinger.",
    "Sister and I were wowed.",
    "Sometimes you have to stand up for yourself or you'll get walked on.",
    "Then Mom showed us how it was done.",
    "Sister and I scuttled off, eyes cast down, confused.",
    "Keeping his head down during the swing had new meaning.",
    "By the eighteenth hole, they were jumpy.",
    "Every golf shot sounded like gunfire, and vice-versa.",
    "They'd swing and duck. Hit and run.",
    "But Dad wanted to do it the right way.",
    "He withheld judgment of shots.",
    "I was sure he had it turned around.",
    "I didn't want to work at something that was supposed to be fun.",
    "I'll never forget one of our early outings to the course with her.",
    "One man took a practice swing on the elevated tee directly behind us.",
    "But Mom, all five-foot-three inches of her, wasn't one to back down.",
    "That didn't mean love or life was without challenges, though.",
    "That Dad could count on this shot with regularity gave him confidence.",
    "Caught in enemy cross-fire, the commander refused to call it quits.",
    "When he returned home, he didn't waste time asking for Mom's hand.",
    "He wanted us to see that golf was a game of possibilities.",
    "What amazed me most were the things she could make the ball do.",
    "Well, Dad would pump us up: Swing like you know how.",
    "Dad's brown wingtip spikes made a great clack on the pavement.",
    "Sister and I could barely make out the flag at the end of the hole.",
    "If the shot didn't go as well as we liked, he'd toss us another ball.",
    "As part of the deal, Dad promised to keep Mom on the golf course.",
    "He is everything they say he is, too, she recalled to me.",
    "Hands like horses' hooves.",
    "A guest snapped a photo and sent a copy to her.",
    "I stared at that photo a lot.",
    "At age eight, I didn't know what to think.",
    "Not in a bad way, Mom recalls, smacking her lips.",
    "No, Dad said, he didn't.",
    "But back to her dislike of wrinkled shorts.",
    "A good swing doesn't need flaunting, Mom said.",
    "And she sternly advised Dad, Look but don't touch.",
    "A gentleman doesn't think with his muscles.",
    "Then she'd step outside of her car to zip them up.",
    "Keep your thighs firm on the downswing.",
    "The locker–room attendants spied on her with binoculars.",
    "Afterwards, he patted her on the back for well–done leg action.",
    "However, this proved to be an ideal arrangement for both.",
    "While caddies called her Fanny, golfers tagged her End Joys.",
    "Wives didn't trust her and snubbed her on the course, but not Mom.",
    "She had prize ribbons and a leather riding crop to prove it.",
    "Mom made the swing look so easy.",
    "Or of a vase shattering from an overzealous swing.",
    "Martin demonstrated his smooth swing, and we were putty in his hands.",
    "When he struck a ball, it sounded like a bite of a crisp apple.",
    "How long will it take to get your swing?",
    "How long do you have? He winked playfully.",
    "The Assistant Head Pro helped at those clinics.",
    "Dinner talk turned from birdies and bogies to bombs and radiation.",
    "As I ran toward my ball, it dawned on me that I was seeing The Big One.",
    "Don't look up or you'll lose your eyes, said my teacher, Mrs. Bobbin.",
    "Whatever the case, Dad stuffed that photo in a drawer.",
    "What was it about small men bent on big destruction?",
    "So our family of six headed to the course–with a game plan.",
    "If they got their chance, they'd overthrow Fidel's regime, as well.",
    "I was never certain to what extent fear motivated his decision.",
    "Dad walked over to his next shot.",
    "Would I ever get to hit a golf ball again?",
    "That's when Dad took charge.",
    "Grandpa Wallace was an official Civil Defense Block Warden.",
    "Should the bomb drop, his job was to direct neighbors into his basement.",
    "Dad supplied us with a stop watch to clock ourselves.",
    "Mention Fidel, Dad would shake his head in despair.",
    "He'd rather be out golfing with his family late afternoons.",
    "I doubted that Dad had a secret strategy to bail us out this time.",
    "Fidel had beaten us all.",
    "He picked up his ball and nodded to Mom. Rain, I heard him say.",
    "A deep breath of relief emptied through my body.",
    "I had fourteen strokes on the first hole, and was ready to quit.",
    "He hugged me like he knew how much this game meant to me.",
    "He asked questions, Which way is your ball flying?",
    "Straight, left, right? High or low?",
    "Tell me what you're thinking about when you swing the club back?",
    "Do you hang on to on past swings?",
    "Then he'd fire back suggestions.",
    "Try gripping the club more like this.",
    "Hit the bottom of the ball instead of the top.",
    "Let bad swings roll off your shoulders.",
    "I was sad when both he and Martin moved away.",
    "Mom liked how he taught, and she often took me with her to her lessons.",
    "Firm up your left leg on the finish, he would tell her.",
    "Mom was apprehensive about putting us in someone's hands.",
    "Eventually, he moved to the Midwest to start a horse ranch.",
    "For a brief while, a Young Head Pro blazed in.",
    "Eddie was in his early twenties and by that time, I was sixteen.",
    "Eddie liked Dad's Olds 442 Cutlass; Mom approved of Eddie's swing.",
    "He also was an excellent teacher of the swing.",
    "He also had a lot of other deals in the fire.",
    "If there was time, Trigger would watch me swing and give me tips.",
    "Soon after that tournament, I heard his life went topsy–turvy.",
    "He began investing in racehorses and spending more time at the track.",
    "Under his direction, a lot of swings at the course improved dramatically.",
    "But Eddie crossed the line and was caught sleeping with another's wife.",
    "Afterwards, he dropped his eyes.",
    "Better not tell your mother, he said.",
    "The last time I saw him was the day he'd been fired.",
    "He was collecting his things from the pro shop.",
    "I didn't know what to say.",
    "He'd given me such hope for my swing.",

    "I was wrong, Eddie said to me.",
    "I broke the rules.",
    "Well-wishers stood around him, offering to find him work close by.",
    "We all wanted to follow him.",
  ],
  medium: [
    "Mom, pressed cheek to cheek and in the arms of a man who wasn't my father?",
    "He had us practice taking shallow breaths so as not to use up too much oxygen.",
    "Those days, Dad's face, usually round and bright–eyed, turned fretful and long.",
    "A Cuban museum is devoted to those failed assassination attempts and plots.",
    "He had one golf lesson in his youth, and maybe a couple more after that.",
    "Mom secretly hoped she'd be presented the engagement ring on the course.",
    "A fairway bunker was nothing compared to the hazards of a sniper in the rough.",
    "Just about anything that would fall from a tree or land at her feet.",
    "Mom and Dad hung it proudly on the hallway wall along with our other family photos.",
    "It was well known that she didn't believe in wearing underwear, either.",
    "We couldn't stop the clock until all four of us kids arrived at his house.",
    "Was there a skirmish? Did my dad protest, maybe throw him a punch?",
    "They both agreed, however, that she'd been endowed with true swing talent.",
    "End Joys had already been through several husbands before taking up golf.",
    "Between songs, when Dad went off to get Mom a cold drink, Arnold moved in.",
    "One of the most masculine men, with or without a swing, she's ever met.",
    "The weeks following, much to Mom's delight, Dad started swinging from his heels like Arnold.",
    "Mom was giddy with excitement. Then, for the most part, she became herself again.",
    "Every time I heard the story of End Joys, it grew to voluptuous proportions.",
    "Or that one had anything to do with the other until I accompanied Mom to a lesson.",
    "Set up to the ball with your hindquarters nice and high, the pro told her.",
    "It was on the back nine of a hilly course in northern China that the shooting began.",
    "My brothers skipped alongside, their hands spilling over with soda and candy.",
    "He motioned us over to a ledge of grass. Below that, the world grew bigger and greener.",
    "On the first tee, in my shorts, cotton blouse, and tennis shoes, I squinted into the sun.",
    "From the start, Dad's family plan was to give us four kids a positive spin on golf.",
    "Aunt Margaret believed that I would find the best swing in my own shadow.",
    "Facing the dresser mirror, she could view the entire swing in that mirror.",
    "We're going out to play, they'd holler at us four kids and the babysitter.",
    "After that day, not only did I crave Mom's swing, but I wanted Dad's power.",
    "Then he gripped a wood club, gathered himself up like a bear and lashed out.",
    "I spooked at the cracking sound, thinking it was my head that shattered.",
    "Nevertheless, I couldn't ignore his tactics because they seemed to work.",
    "Once we understood this, he felt sure we'd make our way through life just fine.",
    "With his dead-eye aim, he taught us how to line up putts and read breaks in greens.",
    "She also didn't like that boys talked to her chest or assumed that they ruled the world.",
    "Your swing will not fail you, he'd say. Only your thoughts will— if you let them.",
    "A foursome of men arrived on the first tee just as Sister and I were preparing to hit our drives.",
    "He reminded us, Never let fear rule your decisions. Even if the ball was tangled up in roots.",
    "She'd given up on making her mark on the high school hockey field or tennis courts.",
    "From that day on, until Betty left, she didn't want to give him the idea that she was a pushover.",
    "This intrigued me to no end, the idea that the club was alive with power——even over Mom.",
    "Then, off they'd go, bumping through the kitchen door, bags of clubs rattling across their backs.",
    "She could sling a 7-iron past her hips faster than Dad could fling burgers onto the barbeque.",
    "What women were swinging back then, in the early sixties, other than Mom and Aunt Margaret?",
    "Life isn't as simple as you think, she explained to us, her rebel accomplices.",
    "I knew she was trying to teach me something big and wonderful, but I wasn't so sure.",
    "She was dancing up a storm that night to Frank Sinatra tunes with Dad.",
    "She quickly squelched our quarrels with alluring buckets of shiny, white balls.",
    "One night Mom got carried away and miscalculated the height of her backswing.",
    "If he ever tried to take that away from her, she quite possibly would kill him.",
    "You know what it's like to stand on the first tee? Jitters, hopes, expectations.",
    "She'd swing, the ball would fly high, low, slice to the right or hook to the left.",
    "Walking and swinging, shot after shot, she'd advance the ball toward a distant red flag.",
    "There was a bench on the par-3 seventh hole where they liked to hold hands and talk.",
    "At the dinner table, when we kids asked where he got his power from, Mom pointed to his stomach.",
    "Dad could see soldiers in the trees aiming rifles at them from a fifty-yard pitch shot away.",
    "He was a twenty-three year old ensign assigned to a heavy cruiser stationed in the China Seas.",
    "The commander knew Dad was a low-handicap golfer, and ordered him to bring his clubs along.",
    "After a week, Mom, resolving to finish, dragged her bag along the final hole in near exhaustion.",
    "Ever the straight-shooter, she placed her ball carefully on the tee as though lighting a fuse.",
    "Dad handed each of us a club and ball, and told us, All you want to do is have a good time today.",
    "She polished her pre-swing waggle: a sassy wiggle of her extraordinary heart-shaped rear.",
    "Only later did I understand that when all the pieces flowed together, it was called good timing.",
    "Dad was there too——they were last minute guests of someone who knew Someone.",
    "She'd set off a trail of sparks on the green shag carpet and around her stockinged feet.",
    "End Joys would drive to the course with her shorts unzipped so she would look freshly pressed.",
    "He thundered and crashed through the crowds to clear the way for this queen of the night.",
    "As the cloud shadowed the fairway, I scowled at the wicked forces that had cut short my life.",
    "Instead, we huddled in front of the TV, listening to Walter Cronkite's latest updates on the Scare.",
    "Mom wore a pink knit dress, cinched at the waist with a wide gold belt and gold hoop earrings.",
    "Nevertheless, she heartily defended golf by pointing out the drawbacks of more popular sports.",
    "My green-eyed Mom looked incredibly agile and loose-limbed swinging a club around the house.",
    "Uncle Bill said that it was essential to swing with my ears plugged and he offered cotton balls.",
    "Feeling like little savages, we'd take off our tennis shoes to grip the cool grass with our toes.",
    "He'd stand with a club in his hands, dislodging Wiffle balls, like ripe fruit, from the trees.",
    "Renewed, Mom would return to the kitchen to dish out bowls of rocky road ice cream for each of us.",
    "On the greens, whenever she sunk a long putt, she'd prance on her toes while retrieving the ball.",
    "Her hair, piled in wide equally spaced curls on top of her head, bounced like a coiled Slinky.",
    "As a result, she felt that her mind was cluttered—unlike when she first took up the game.",
    "His swing unfolded like the opening of an accordion–expanding with each rhythmic motion.",
    "At the peak of his swing–when his timing and rhythm was right–he was unbeatable.",
    "Both women and men golfers agreed, he was a fun flirt and stimulating to talk to over a beer.",
    "If I could work with you for one more year, he said a week earlier, You'd be swinging good as a pro.",
    "Of course, he said that to all his students, young and old, male or female.",
    "I thought I was going to cry in front of him–crying for him, but for also for me.",
    "Some golfers felt that the woman was as much to blame for the firing of this gifted Head Pro.",
    "One time he had her pound on his left thigh with her knuckles, just to get his point across.",
    "Mom dropped me off to follow him in a Tour tournament in town at El Dorado Golf Course.",
    "He had a terrible time, I don't know if my presence brought him bad luck, but I took the blame.",
    "Dad gave us his explanation–that it was one of those hazards that comes with the territory.",
    "But even after they were first found out, their trysts resumed, to a feverish pitch.",
    "So I turned to some of our golfing relatives hoping they could tell me the quickest way to a swing.",
    "Horseback riding broadens the haunches, skiing overworks the thighs and wind-burn parches the skin.",
    "Payments for the Encyclopaedia Britannica were overdue and we needed a new lawn mower",
  ],
  long: [
    "After winning his first lawsuit, Dad plunked down two thousand dollars to join a golf club five minutes from our house.",
    "Both Mom and Dad wanted to make little golfers out of us kids, but Mom was especially grateful to have a place where we could run loose and she could get out of the house.",
    "Martin was the Head Pro at the club, dark–haired and of chiseled jaw, an impeccable dresser in slacks, sport shirt, and cardigan sweater.",
    "He wore black–rimmed glasses that made him look like he should be called a professor of golf instead of a golf professional.",
    "Though she'd decided it was time to put order into our swings, she was equally fretful about filling our heads with confusing swing notions.",
    "Her own insatiable curiosity for the swing had led her to feed voraciously off the tree of knowledge.",
    "She studied instructional books, listened to everyone else tell her how to swing, and took lessons from pros touting complicated theories.",
    "Those were the pure days—Mom, a teen, tagging alongside top amateur golfer, Betty Hicks, and mimicking Betty's rhythmic swing.",
    "But Mom trusted Head Pro Martin to teach us because his swing seemed so effortless and refreshing like the flight of one thousand doves, not that of some lofty impresario.",
    "Sister and I marched dutifully to the practice range to join his summer junior clinic while our brothers ditched into the bushes to light firecrackers.",
    "One day he sang to me in the pro shop: She has freckles on her but she is pretty. She has freckles on her but she is nice.",
    "Patrick found me crying in the club storage room after a round in which I panicked during the junior club championship.",
    "The next Head Pro, Trigger, was a quiet, tall and skinny man with a long nose who swung quickly, succinctly–a blur of color.",
    "He'd played on the Tour for a few years and had what some called a wristyswing like the old–time players.",
    "He divorced his wife and hired Mom's decorator–friend to turn his house into a bachelor pad with dimmer lights and mirrored bedroom ceilings, leopard skin and leather.",
    "Stocky, with muscular legs and forearms, thick, wide palms and a small gap between his front teeth, his swing was down to earth, all meat and potatoes.",
    "He was emboldened by a string of good showings in local pro tournaments and was hoping to make it on the big Tour.",
    "She hung around the range in short skirts, tight blouses, and wide dark glasses like a Jacqueline Suzanne character in The Valley of the Dolls.",
    "She wasn't about to give up her comfortable life for this Head Pro, but she wanted to savor the diversion from her housewifely doldrums.",
    "You always want to hire a Club Pro who fits the part (good manners, nice dresser, personable), but then you have to hope that he's not just a good–time playboy out to keep score.",
    "But then someone suggested that perhaps we'd become psychologically hung up on him and that we ought to give the next Head Pro a fair shake at our swings.",
    "By age fourteen she'd grown to hate her too short, too-freckled, too-bosomy, too far-sighted, too-bookish, too red-headed self.",
    "Taller, leggier girls seemed to have the advantage of both speed and strength, which only fueled her competitive fever and made her feel as though she was missing out.",
    "Borrowing her Dad's whippy-stick golf clubs, she sought refuge at the course across the street from her house in Long Beach.",
    "Though she had little idea of the swing, she discovered that a metal-headed club could be used as an ax or wand.",
    "It thrilled her to attack the ball, to spin her body up into a bee-hive of power and emotion and then let loose with a sting, zinging like a slap across a lecherous boy's face.",
    "Other times she found that a lighter touch, something most of the boys she'd observed couldn't bring themselves to try, worked like magic, especially around the greens.",
    "Before long, she noticed that a well struck shot commanded attention and respect, and for someone as small and unsure as she, that was a big deal.",
    "Mom's hopes for becoming an accomplished golfer blossomed the day she saw Betty Hicks swinging across the fairways with power and ease.",
    "It turned out that Betty was even shorter than Mom, but in a good Santa Ana wind, her ball could carry twice as far.",
    "As a kid, I thought I knew everything about Mom until I discovered her habit of swinging: on the lawn, living room, bedrooms, hallway, bathroom, and kitchen.",
    "Other than a club, she'd use a rake, a broom, a stick, a spatula, a baseball bat——whatever she could grip her hands on.",
    "She'd strike at plastic Wiffle balls, lemons, avocados, magnolia seeds, Ping-Pong balls, the dog's old tennis balls, Dad's wadded up socks.",
    "Over the flap of wet clothes tossing in the dryer, I could make out the repetitive sound of our lawn being gutted, piece by piece.",
    "I'd hear the roar of the upright Hoover approaching my bedroom door, knowing she was grooving a smooth path to an electric putting machine.",
    "She'd make a great whipping, swishing noise with a club that could shake a lamp, unfurl curtains, or rattle a tree.",
    "Swinging in front of her full-sized bedroom mirror, wearing only a lacy Maidenform bra and silk half-slip.",
    "The swing made her white skin hot with color, and her red hair would tumble from its French twist, bobby pins falling to the floor.",
    "She didn't get worked up. She just gathered the pieces and laid them on the table to glue together later on.",
    "What amazed me was the possibility that she might not know what her swing was doing at all times. As if it had a mind of its own.",
    "Sunday was the one day of the week Dad didn't go to the law office, and Mom wasn't running off to a community meeting.",
    "After church, they couldn't wait to shed their dark church clothes for matching sporty outfits in bold tropical and plaid prints.",
    "They'd return at sunset, their cheeks sun-kissed, hair wind-blown, grass cuttings on their legs, shirts untucked, laughing like kids.",
    "It was a mystery to me what they did with those clubs for four hours at a time while I played kick-ball with my friends.",
    "Her skill seemed to me no more useful than baton twirling and having nothing at all to do with the sweat and punch of real sport.",
    "As far as I knew, not my best friend's mom, not my second grade teacher, not Barbie Doll, not Jackie Kennedy, not Joan Baez, not the Supremes, not Jane Fonda.",
    "I'm doing what few women do, Mom told me. To her, golf was the next best thing to climbing Mt. Everest.",
    "Tennis jars the joints and face muscles—though she herself was very accomplished at all of these sports.",
    "I figured it was something that could be handed off to me like a birthday present or caught like a cold or fall into my hands through a crack in the universe.",
    "However, when she showed me how to grip a club and swing—and I missed the ball entirely—I wanted to quit.",
    "The advice I got was daunting to me, a strawberry-haired girl in cut-offs and rubber flip-flops with a big dose of impatience.",
    "Grandpa Wallace told me that I should try to swing the head of the club like a gong so that it would strike me in the head at the start and the finish.",
    "Undeterred, he'd throw rocks at her feet until she'd agree to climb down and play a few holes with him.",
    "He'd cock his head one more time to check his aim which was always extreme left—the next fairway over.",
    "During long summer days, armed with clubs she called weapons, Mom began taking us to the course near our home in Long Beach.",
    "We'd hit with abandon, running up and down the fairways and hills, sometimes on one leg or with one hand, balls flying forwards or backwards, it didn't matter.",
    "My brother Don, hipless as a snake, held his pants up with one hand and dragged an old set of Dad's clubs behind him with the other.",
    "Alex, the eldest, slumped to the grass and cried whenever he lost a favorite ball to a lake or the bushes.",
    "Sister and I got poked in the chin swinging clubs that were too long. We tired easily in the hot sun.",
    "I soon learned that the game wasn't always easy for Mom like I'd thought. Certain shots rubbed her wrong.",
    "Especially worm burners—balls that rolled on the ground—or fliers that sent her into the woods and drained color from her face.",
    "If she strung more than five dingbats in a row, we could count on eating frozen peas and fish sticks for dinner instead of roast.",
    "However, later in the evening she'd usually be at it again, swinging under floodlights in the backyard.",
    "No matter where the balls flew, Dad——ever a team player——would applaud her from his vantage at the end of the garden.",
    "She'd take a stance in the mud or from behind a prickly tree, or toss a pinch of grass in the air, or get down on her hands and knees to sight a line.",
    "Mom's gutsy attitude landed her in the heart of controversy, whether running PTA meetings or staking a claim on the course.",
    "Then, as if we were invisible, he set up to the ball and aimed his shiny metal-shafted club right over our pig-tailed heads.",
    "But then we saw Mom's size-five white golf shoes moving quickly toward him, her flowered Lilly skirt fluttering around her knees as she marched up the bluff.",
    "She caught his attention with a brisk wave of her pink gloved left hand and in her most reasonable voice, delivered her message, Gentlemen, this is our starting time!",
    "Those men looked ominous standing there with their clubs and big leather golf bags, grumbling in voices deep and gruff.",
    "She put her hands on her hips and said something I couldn't hear, and before I knew it, they were nodding their heads and stepping aside.",
    "She flexed her knees and made a mighty swing that wrapped the club around her shoulders, smacking the ball good and hard, like she was splitting the fairway wide open for us.",
    "He'd go along quite agreeably with each pro's suggestions, but afterwards would go right back to his true blue swing.",
    "Tall, athletic, and barrel-chested, he'd hover over the ball in a wide stance, with lowered right shoulder as if bracing for a strong wind.",
    "Then summoning concentration, he'd make a grand upright sweep of the club and bring it back to the ball with a driving punch of wrist and arms.",
    "The resulting shot would be a banana ball to the right that no one, except Mom, ever believed would make that sharp turn in time to find the fairway.",
    "He befuddled fierce competitors who'd throw adolescent tantrums when their groomed swings sent balls wayward into the woods or duck pond.",
    "Over the years, a lot of people, including myself, tried to convince him to aim straight. He'd gently nod toward his ball lying in the middle of the fairway.",
    "Dad played golf during high school at Long Beach Poly and that's when he met Mom. Roaming the neighborhood golf course, his eyes were drawn to her swing and vibrant red hair.",
    "Whenever he strayed from his foursome of spitting, cursing teenage boys, she'd timidly drop her clubs and scale the nearest tree to get away.",
    "According to Mom, she—a tiny thing to his six foot three—kicked my father good and hard and often to let him know that if he wanted her, he must defer to her number one love.",
    "Her passion enamored Dad. By the time he went off to Annapolis, he'd decided that she, the sixteen-year-old sportswoman, would make a terrific wife and mother.",
    "At Annapolis he competed in lacrosse, football, Ping-Pong, and boxing——playing golf in his spare time.",
    "That's when he took a bit of knowledge and technique from each of those sports and parlayed them into his golf swing.",
    "He knew that a strong right cross to a boxing foe's ear could knock him out, and that the same principle translated to a golf swing would make a big impact on the ball.",
    "In boxing, too, he learned to be light and quick on his feet, and took that dance into his golf swing.",
    "He called upon the wrist action of a back-spin serve in Ping-Pong whenever he wanted a golf ball to bite or stop on the green.",
    "By the time the navy sent him to China in 1947, he'd settled comfortably into a one woman-one swing theory.",
    "My mom hadn't agreed to marry him yet, and the fact that he was a golfer almost got him killed while on duty.",
    "He'd heard that there were challenging courses in China, which he hoped he could play before Comrade Mao got a hold of the country.",
    "Within weeks, the political situation grew tense with the communists battling Chiang Kai-Shek's forces.",
    "Even so, the commander ordered Dad, the assistant medical officer, and another shipmate to shore for a game.",
    "They also were dropping mortar shells from the hillside into the rough, persuading the golfers to avoid hunting down errant balls.",
    "But the commander assured him that the soldiers were just firing at the ground and over their heads to scare them.",
    "That day, Dad gained a key insight to lifetime enjoyment of the game: Standing over anything too long isn't healthy.",
    "In Mom's parent's house, Dad made his good intentions known to his future father-in-law who sat, nodding his head in a silk smoking jacket.",
    "They spent their August honeymoon in San Diego, each day playing tennis in the morning, followed by 36 holes of golf.",
    "The summer of '60, before I turned eight, he drove us in his Chevy wagon through our tidy Long Beach neighborhood of cement sidewalks and shuttered stucco houses.",
    "He turned down a shady street of oleanders and eucalyptus where the road narrowed between the two flagstone pillars that marked the golf course.",
    "He and my brothers took off toward the pro shop to fetch a brown leather pull cart for Mom and a canvas carry bag for himself.",
    "Sister and I followed Mom into the ladies' locker room where she kept her golf shoes, Swiss Army Knife, Doublemint Gum, Saltine Crackers, Vienna Sausages, beige stockings.",
    "Mom's finger traced a speck of a white ball in blue sky until a magical cloak of green rose up to swallow it.",
    "As if we needed convincing Dad rose from the table so we could take turns hammering away at his round but firm belly.",
    "But Dad soon proved that strategy, more than strength or a perfect swing, was the best way to get around a course.",
    "He knew about percentage shots—when to hit right through a tree, to aim for the flag stick, or hold back.",
    "A ball that rolled on the ground was no less than one that flew in the air—they both had a chance to put you closer to the hole.",
    "Most of all over that first summer on the course, Dad wanted us to realize that the world wasn't going to end with one miss-hit.",
    "Arnold Palmer eyed Mom as she trotted by him at the crowded cocktail party during pre-tournament festivities for the Bob Hope Desert Classic tournament.",
    "This was during the days of martinis, frosted pink ice lipstick, Zippo lighters, plastic bauble beads, and men's gold rope chains.",
    "Never one for polyester and chains, he preferred to charm her with masterful footwork that kept her on her toes.",
    "Dad didn't mind Arnold swing dancing so close to Mom in the shimmering night, saying, I was the real winner that night. I got to go home with the prize: your mom.",
    "Tan and dazzlingly handsome in dark suit, white shirt, and tie, he stepped up behind her like a prizefighter and wrapped his burly forearms around her waist.",
    "When the music started, he danced like he swung, from his heels hard and steady, twirling Mom with his powerful right arm.",
    "Before releasing her back to Dad, Arnold told her that she was the most ravishing redhead in the room.",
    "She was a woman at the course who Dad recalled once or twice as being loads of fun to watch, and Mom described as no one's mother.",
    "She apparently found her true sport in golf, and practiced long hours on the putting green and range.",
    "She had a white streak in her coffee-black bouffant hair, and wore tight bermudas and see-through blouses.",
    "She felt it interfered with her swing; she claimed that she was allergic to the elastic in bras and panties.",
    "To get an idea of how far she'd go, she refused to ride in the golf cart with her latest husband, an insurance agent. Instead, she'd walk ahead of him.",
    "There'd she be, every afternoon, on the practice green, bending over to line up putts, or taking a wide stance on the range, under the watchful eyes of a pro.",
    "When men passed by, they'd croon to each other, If this is my dying day, then please, lord, let her be my End Joys.",
    "Mom appreciated a good swing (though the few times we saw End Joys, Mom forbade Sister and me to grow up looking like her).",
    "Before hearing of End Joys I didn't know that people were thought of in sections like fryer chickens-arms, legs, thighs, hips, hindquarters, breasts.",
    "Or that the golf swing was likewise broken down into parts—grip, set-up, backswing, downswing, follow-through.",
    "Toward the end of my first summer playing golf, President Fidel Castro—an avid golfer himself—was busy bulldozing courses in Cuba.",
    "In Dad's eyes, this was the worst kind of killjoy—a man who was stockpiling nuclear missiles and wiping golf off the map besides.",
    "I was vaguely aware of Fidel's passion for golf because of a newspaper photo that Dad had clipped, a black-and-white image of Fidel putting with revolutionary Che Guevara.",
    "Wearing military fatigues and berets, the two men made an impressive bearing on the green at the Country Club of Havana.",
    "Fidel's stance was wide, as if intent on protecting the ball, his head tucked down into his neck like a hunched turtle.",
    "Though it was said that Che let him win that day, a short while later Fidel plowed under that course—and every other course in Cuba but one—as part of his crusade against the evils of capitalism.",
    "Golf was played by the bourgeois villains who were out to exploit his poor country for rum, sugar and cigars.",
    "Not long ago I read that there have been at least 637 assassination attempts on Fidel's life, and I could imagine no more dangerous place than standing over a putt or swinging from an elevated tee.",
    "She and Dad felt that all golfers should be ambassadors of good will, and every problem of the world could be resolved on the fairways, not fields of war.",
    "In fall of '62, about the time my sister, brothers and I headed back to elementary school, we learned that Fidel was now aiming his weapons across the water at us.",
    "As he and Soviet Premier Khrushchev pressed their historic confrontation with President Kennedy to the brink of apocalypse, spy planes captured photos of missiles stacked on empty Cuban fields.",
    "Dad heard through the military grapevine that California was one of the main targets, specifically our neighborhood, a stone's throw from Douglas Aircraft, the U.S. Naval Weapons Station.",
    "With the threat so close to home, Mom loudly damned–all–wars–to–hell while stocking up on great supplies of Campbell's soup, Bumblebee tuna and Vienna sausages for our makeshift stairwell shelter.",
    "Neighbors–non-golfers among them–patrolled the streets at night armed with golf clubs to ward off sneaky Red infiltrators.",
    "Once a week in school, when emergency test bells sounded, we filed out to the hallway, dropped to our knees, and covered the backs of our necks with our hands.",
    "Nights, I'd pull the covers over my head, listening for the low buzz of a missile approaching our house, waiting for my body to vaporize into ash.",
    "My brothers set up a crow's watch on the roof hoping to catch sight of the squiggly contrails of enemy missiles lighting the sky.",
    "Sometimes, when the winds switched and blew out to sea from the deserts, a pink haze—a trickle of fallout—filled the horizon where another nuclear test bomb had been detonated near Las Vegas.",
    "When Kennedy announced to the world that we were on the brink of destruction, we listened in disbelief as the enemy responded with a doomsday message: They planned to bury us.",
    "Fed up with living under bullies' threats, he and Mom agreed that it would do no one any good to wait around for the end of the world.",
    "At Dad's command, sometimes in the middle of a swing, we were to drop our clubs and see how fast we could run across acres of fairways and four city blocks to Grandpa's house.",
    "The same dreaded mushroom shape that my brother Alex had depicted in a poster at school for which he earned a reprimand from the principal.",
    "On these dry runs we'd holler a code word at the side door near his black bug box that electrocuted flies, mosquitos, and anything that snagged its wings on the hot wires.",
    "Then Grandpa Wallace, wearing his official white steel army hat with the red civil defense logo, would lead us down the steep wood stairs, past the wine cellar, to the basement.",
    "There we'd collapse among a maze of short wave radios and battery powered lights, sipping water stored in Welch's grape juice jars and nibbling from tins of oatmeal cookies baked by Grandma.",
    "Of course, Fidel prided himself in keeping a steady head under pressure, along with possessing a certain uncanny invincibility.",
    "Then he'd shoo us back to the course where we'd resume our games–panting and swinging on wobbly legs and adrenalin.",
    "Mom, wanting to believe that Fidel was especially short, like herself, wondered if the world had another Napoleon on its hands.",
    "But one day, toward the end of the week when hope for peace had all but faded, we were caught off guard.",
    "Up ahead, suspended behind the 16th green, loomed a massive, billowing cloud–ominous, gray and top heavy.",
    "He stared grimly at the sky while I glowered at the earth, terrified of his prognosis, awaiting his command.",
    "Then I marveled that such a thing as hitting a small ball off the ground and into the air could make me burst with hope.",
    "So perhaps his wanton destruction of courses stemmed only from too many miss–hits and scores in the 100s.",
    "Every day that week of the Cuban Missile Crisis, we'd run as fast as we could to try to improve our time.",
  ],
  combo: ["#long#", "#long#", "#long#", "#medium# #short#", "#short# #medium#"],
  origin: ["#combo#"],
});

grammar.addModifiers(tracery.baseEngModifiers);

const getTweet = function () {
  return grammar.flatten("#origin#");
};

module.exports = getTweet;
