const tracery = require("tracery-grammar");

const grammar = tracery.createGrammar({
  short: [
    "Sometimes you have to stand up for yourself or you'll get walked on.",
    "Nine holes zipped by.",
    "I wasn't tired at all.",
    "Don't keep them waiting, he said, slipping a quarter in my palm.",
    "And here's a little secret.",
    "Afterwards, over rummy lessons and root beer floats in the grill, Grandpa confided.",
    "These old birds would kill me if they knew I told you.",
    "Both have been club champs, the taller guy threw the javelin in the Olympics.",
    "His mind went to work.",
    "By night, he sang in the clubhouse cafe.",
    "Mom said he was also handsome beyond belief.",
    "It was more about rhythm.",
    "It was a long, windy road from Long Beach to the lone desert resort.",
    "However, Dad wasn't sure if a person could be franchised.",
    "Mom took out one of Dad's business cards from her purse.",
    "The rest of the year, Maurice taught golf at Gilman Hot Springs.",
    "They wanted to do something for Maurice, but didn't know what.",
    "Dad had been pondering investing in the franchise himself.",
    "They signed up to play in the Gilman Hot Springs Invitational.",
    "On the back of the card, she scribbled in pencil.",
    "We are golfers and honest business people with your best interests at heart.",
    "Then she erased it and wrote.",
    "You should be a big star and we would like to help.",
    "But somewhere between the last song and martini, they lost the nerve.",
    "They shared their thoughts with some of the other couples.",
    "We ladies were trying to figure out how to keep him for ourselves.",
    "But Dad and the husbands were thinking along the lines of franchise.",
    "I think I fell asleep because I don't have any memory of him.",
    "They'd never seen anyone hit a one iron before.",
    "In fact, they'd been told by their husbands that only God could hit a one iron.",
    "But Maurice showed them how it was done on a long par-three hole.",
    "He has an expert's eye, Dad said.",
    "I didn't know at what Grandpa was an expert.",
    "He was so tall he had to duck his head under door jams.",
    "Grandpa couldn't snow-ball anyone with his golf ability.",
    "He, admittedly, had a lousy swing.",
    "I understand you've outgrown your clubs.",
    "I'd like to give you a new set for your thirteenth birthday.",
    "I'd never thought to look for him behind the huge tinted window.",
    "Reinforcing what we suspected - that he was larger than life, an alien, even.",
    "Little did I know, Grandpa was well aware I loved golf.",
    "My clubs shined in the corner of my bedroom all night.",
    "The next day I rushed to the course to try them out.",
    "Along with a pair of golf shoes - my own - not my mother's.",
    "There was nothing else that I would ever want more.",
    "It was all I could do to stay on the ground.",
    "I was ready to impress Grandpa.",
    "I couldn't wait to show him how I could swing those clubs.",
    "I grabbed my bag of new clubs and ran to join them.",
    "Without a practice swing, I stepped up and swung.",
    "The ball landed on the par-three green.",
    "Then, it was over.",
    "On the tee, my heart pounded, my thoughts whirled, dizzily.",
    "Their huge leather golf bags were strapped to gas carts.",
    "Grandpa and his friends cheered and clapped.",
    "Grandpa was the one who surprised me, though.",
    "From the start, I could see that our games were different.",
    "The one man could not take the club back past his waist.",
    "When he had enough shots, he simply pocketed his ball.",
    "Watch me.",
    "She stepped up to the ball and shut her eyes.",
    "She swore she didn't peek.",
    "The ball zipped far down the middle of the fairway, like all her other shots.",
    "She was a living swing machine.",
    "I chickened out and swung with my eyes open.",
    "As we headed down the fairway, I tried to form the right question.",
    "Finally, I asked, How do you know what you're doing?",
    "Before Amy, I took pride in my dexterity.",
    "If I wanted a ball to go higher, I'd use the club to scoop my shot.",
    "To make a ball fly farther, I would swing faster and harder.",
    "Indoors?",
    "What a horrible thought! What kind of parents did she have?",
    "The biggest problem being that Amy had one repeatable swing and I had many.",
    "I never swung the same way twice.",
    "I did some research.",
    "I was stunned.",
    "Then I'd spring to my left side, attacking the ball as hard as I could.",
    "Falling backwards in the process, cutting a fresh blister on my palm.",
    "It didn't exactly matter how far off line my shot went, just that it went far.",
    "I wasn't yet taken with the idea of working on lowering my score.",
    "I'd rather power my way to the finish.",
    "Anxious, I took a deep breath and entered.",
    "Being near Hollywood, I'd suspected otherwise.",
    "I told him that I knew Amy, and his eyes brightened.",
    "There's no one like her, he said.",
    "He offered to take a look at my swing.",
    "The room was dark as an aquarium.",
    "The sound from the shot I hit was deafening.",
    "The ball struck well below the bull's eye target on the netted wall.",
    "I swung better at the next ball, but it, too, strayed low as a bullet.",
    "I wanted him to divine all my untapped potential from those two swings.",
    "He shook my trembling hand and said, Think about signing up for some lessons.",
    "I searched his face for recognition of Amy in me.",
    "Instead I saw what he was seeing - a girl with lots of work ahead of her.",
    "I can help you, but the key is putting in time.",
    "Amy works harder at this game than anyone I know.",
    "Back on the road, Susan Carla and I headed for Sunset Boulevard.",
    "Traffic crawled agonizingly, one long trail of red lights.",
    "I'll never be discovered.",
    "Her voice was small, totally out of character.",
    "If I can't swing like Amy, I announced, I'll quit golf.",
    "I looked up Walter Keller in the phone book and called him.",
    "Mr. Keller, do you give lessons to girls other than Amy Alcott?",
    "He asked me where I lived.",
    "Long Beach, he said, was an awfully long way from his shop.",
    "If I wanted to be a good golfer, he said, I would need to see him often.",
    "When I told Mom, she sighed, It's a long drive.",
    "Our car may not make it.",
    "That was enough of L.A. for us that day.",
    "I was hoping to astonish Walter Keller with my raw swing talent.",
    "She was dying to size him up like all the others.",
    "I remember that day as one big driving contest.",
    "At first, Brian Francis outdrove her by a safe distance.",
    "She was impressed.",
    "But she hadn't warmed up yet.",
    "By the ninth hole, he was only twenty yards beyond her.",
    "I'm scratching your back, she teased, showing her nails.",
    "On the back nine, she gained ten more yards.",
    "I'm nippin' at your heels, she said.",
    "Instead, she wore the latest fashion - culottes.",
    "Men on the club board were divided by culottes.",
    "Neither shorts nor skirt, culottes defied definition.",
    "Then, like a whirlwind, she'd fire away.",
    "She had a thing for fast cars and big drives.",
    "A few years later, Sister married him.",
    "They spoke in secret code language.",
    "For awhile, they made-believe he was 007 and she a Bond girl.",
    "His mom hired Sister to tutor him in French.",
    "Her expectations were rising, and his swing was buckling.",
    "Sister's leg action in those culottes made his Irish blood race.",
    "However, their affections had deepened, and his attention was on the tutor.",
    "Then she encouraged me to sign up for lessons with the new Club Pro.",
    "Her strong, shapely calves were the envy of football players.",
    "She honed her putting stroke on Walter Keller's Electric Putting Machine.",
    "Laura blew into our lives from Florida the hot summer of '68.",
    "You could spot her from a seven-iron away.",
    "I know you'll do well, she'd call after us.",
    "It was unlike any swing we'd seen.",
    "One didn't often see a girl dressed like Laura on the course, either.",
    "But Laura was on to something.",
    "She was winning tournaments.",
    "The local newspaper published her photo on the front sports page.",
    "By age sixteen, she'd become the youngest winner of the U.S.",
    "Women's Amateur.",
    "Magazines were calling.",
    "Wasn't everybody talking about her?",
    "To wear pink polish on our fingernails and mascara and lipstick.",
    "To tan every inch of skin on our arms and legs.",
    "My little champions!",
  ],
  medium: [
    "While Maurice wrapped up the night with beautiful rendition of La Golin Drina - The Golden Dove.",
    "We played courses with names like Los Coyotes, Quail Lake, Soboba, Montebello, Arrowhead.",
    "We woke early, slept in the car while Mom drove to destinations sometimes three hours away from our home in Long Beach.",
    "Until Laura showed up, Sister and I thought we were pretty good with our handful of second and third place finishes.",
    "We were used to hearing our names announced on loud speakers on the first tee.",
    "We could pick out the newcomers - the startled faces of young golfers like ourselves, shadowed in visors.",
    "New balls, the rattle of clubs in vinyl bags across our backs, those first tee shots, whispers, speculations.",
    "Mom dropped us off with lunch sacks of Oscar Meyer baloney and apple juice.",
    "However, Laura upped the ante with beauty and skill, shooting low scores while her mom tracked her from the rough.",
    "Unbridled and reckless, Sister and I had swings that burned all the way to the hole.",
    "We were wild in our quest to send that one small object soaring off the ground, bursting with pure strength and rebellion.",
    "Did she also hold it in the palm of her hand and kiss it or did we just think so.",
    "Removing her glove, kneeling on one knee, she'd line the ball in her sights, and mesmerize it - as we cursed - into the hole.",
    "At the next tournament, she had a gallery of strangers, some asking for autographs, some for dates.",
    "Two years later, she captured both the Long Beach and Los Angeles city championships.",
    "We weren't sure how to deal with this except to try to become like her.",
    "And so Sister and I, along with a lot of other girl golfers, kept swinging  -in our newly purchased hot pants and mini-skirts.",
    "We were prepared to wait, forever if we had to, for our own hot streak.",
    "For me, a gawky girl of fifteen, a date with a cute boy was hard to come by as a good swing.",
    "It helped that Sister was strong as a horse, an all-around athlete built for speed, strength, and endurance.",
    "In the water, she could outlap, outkick, outstroke anyone in the butterfly and crawl.",
    "On the ski slopes, she carved tight slalom turns with roller-derby daring-do that sent many a suitor over the edge.",
    "Her attack on the ball was what ultimately drove guys crazy and forever kept me swinging harder to catch up.",
    "In seconds the swing would be over, and the ball would be soaring like a high trajectory missile.",
    "Most of her ideas about male golfers-other than Dad - came from James Bond movies.",
    "She'd been watching them since she was seven, when Goldfinger came to the theaters in 1964.",
    "By the sixteenth, they were neck and neck, and she let him know that she was chewing on his ears.",
    "As for the finishing holes, Brian Francis recalls that he felt lucky enough at that point to hit anything.",
    "On the eighteenth, she smacked a big one, and he carried her golf bag all the way into the clubhouse.",
    "One thing led to another, and soon they were tumbling about on the freshly raked celadon shag carpet.",
    "When his mom detected their imprints, like divots, she grounded him and apologized to Sister for his uncivilized behavior.",
    "As a police officer, he carried the requisite gun and learned to leap into convertible cars and over couches.",
    "He bought her a mother-of-pearl, silver mini-pistol that she kept in her purse, and taught her his favorite head-lock moves.",
    "On the ninth tee, the final hole of a junior tournament, Amy Alcott dared me to swing with my eyes closed.",
    "With a flick of a wrist, her swing took off in a precise sequence of arms, legs, shoulders.",
    "You should be able to make the same swing anywhere, she said, green eyes laughing.",
    "After Amy walked away with the trophy that day, I decided that I had to close the gap between our swings.",
    "Dad volunteered to rig bamboo poles and a fishing net in the backyard to hit into.",
    "I felt embarrassed to want something so very much, so I threw in the towel and tried to forget about ever swinging like Amy.",
    "A few years later, in 1968, the possibility of becoming a Keller girl once again stirred my imagination.",
    "However, it was her first time driving a stick shift, and she stalled the car on railroad tracks near Hollywood.",
    "The second time we struck out for L.A., we were in search of signs from the universe directing us to the right path.",
    "Susan Carla drove us the entire way looking in the rear-view mirror, applying finishing touches to her makeup.",
    "Better yet, to be asked to step into a device like a transporter in which stars were made overnight.",
    "An expert in legal contracts, he suddenly fancied himself branching out in a different direction: entertainment.",
    "Palm Springs, L.A., Pebble Beach! Both Dad and Mom agreed that his kind of talent shouldn't go to waste.",
    "One time a golfer saw her propped against a tree in front of the clubhouse.",
    "His hearing wasn't very good, conversations were loud and repeated.",
    "He commanded us to sit up straight and to learn every word in the dictionary.",
    "Mom, prone to motion sickness, would have to lay down on the grass once they arrived.",
    "The ongoing frustration of Mom and the ladies led Dad and the husbands to take action.",
    "Back home, the town's first McDonald's Golden Arches restaurant had just opened.",
    "But unlike burgers, Maurice had fallen into their laps like a gift from the gods.",
    "Instead of a request for a favorite song, she suggested they slip Maurice a note.",
    "On their way back to their room Dad took out a $20 dollar bill from his wallet.",
    "He had wanted to give him a whole lot more—and placed it in the tip bowl on the piano.",
    "The following year, Mom and Dad took us kids to see Maurice in the Ramona Pageant.",
    "And that's when I'd imagine his swing - especially the day he hit a one iron for Mom and the ladies.",
    "Nevertheless, when I was twelve and my game hit a dry spell, that's who Dad said I should consult.",
    "To tell you the truth, I was intimidated by the man who came over for Sunday dinners.",
    "Still, he smiled a lot, showed plenty of gold in his teeth, and always had a new joke or two.",
    "Communication spelled out in code by a lightning fast tapping with his fingers on a black key.",
    "To get it airborne, he'd floor the gas pedal to the edge of the dusty cliff, and then park.",
    "Then he'd hand the coil of three hundred foot cord over to each of us to try to grasp.",
    "It's always nice to see a young girl swinging so well, he said with a wink, one Sunday after dinner.",
    "And when my birthday arrived late summer, they were exactly what I desired - Wilson Irons.",
    "Tap, tap, tap about the house in my spikes, the sound on the bathroom tile, mesmerizing.",
    "My timing was deliriously smooth...arms flinging...legs pushing...hair flying...the ball soaring farther than ever.",
    "One week later, I met my grandfather at the course for our nine-hole game.",
    "On the first tee that early afternoon, my grandfather bent over to give me a kiss on the cheek.",
    "Hope you don't mind, he said, but these two youngsters are dying to play with you.",
    "I waved hello to the two white-haired, white-shoed men busy stretching their backs, trying to touch their toes.",
    "I tried staring harder at the ball, but it grew fuzzy, soft, dazzlingly tiny.",
    "I couldn't remember what to do next, how to swing, scolding myself, Come on, you've hit hundreds of shots.",
    "Oh, but this mattered so much, so very, very much...my mind drew a blank.",
    "There wasn't anything I could do but give in to whatever swing my body came up with.",
    "The other man said, Helluva shot, no matter where anyone's ball landed, and kicked his ball into the fairway before hitting.",
    "Maurice was an inspiration to Mom and all the ladies he gave lessons to, someone to share swing pasts and paths with.",
    "A man of his size - a tall statue with long arms and legs - I expected him to smack the ball.",
    "But each swing was a slow, flattened heave-ho, as though he was scooping something awfully heavy instead of swinging a club back.",
    "The ball would take off in a low wobbly flight before plopping to the ground, not so very far.",
    "They didn't waste time, drove right up to their balls, hit, and raced off again.",
    "They jingled coins in their pockets and cleared their throats while waiting for their turn to putt.",
    "Grandpa spotted them first - other little golfers like myself gathering on the tenth tee outside the window for a sunset game.",
    "He rose from the card table and tapped the window to gain their attention, pointing toward me.",
  ],
  long: [
    "Dad decided then and there that Maurice should be taken to Hollywood or at least put on tour at different golf clubs, to sing and swing.",
    "A thirteen-year-old Golden Girl, from the top of her long, platinum blond hair to the tips of her black and white saddle golf shoes.",
    "Her swing began with a cat-like stretch of the arms, followed by a sway of hips and tilt of left shoulder under her chin.",
    "At the top of her swing, she'd pause before hopping to her left side, the rest of her tightly wound body unfurling like a cat.",
    "There was nothing finer than sending a shot tumbling into the rough then thrashing through bushes and trees, wielding long irons like machetes, convinced we were tracking tigers, not balls.",
    "We thrived in the shadows, on slippery hillsides, in the creek - the ball whistling through branches, ricocheting off snarly roots and river rock.",
    "Favoring tennis skirts or hot pants, tight tops, hair ribbons to match, she could have passed for a glamourous ice skater performing a clean single toe-loop combination on the fairway.",
    "Maybe she was there to protect her daughter - who was a couple of years younger - from what could have turned into a hair-pulling, nail-scratching cat fight among a gritty pack of girls who had gotten along fine with make-shift swings and down-to-earth looks.",
    "Boys and fathers followed her around the course, cheering her on like fans at a beauty pageant, counting their blessings and her strokes.",
    "There was the clatter of spikes on pavement, the usual nervous silence as we checked in, received official scorecards, instructions, pairings.",
    "That July and August, Sister and I competed in junior tournaments every week, all over Southern California, while our two brothers attended football camp on Catalina Island and hiked the Sierra with other Boy Scouts.",
    "A thirteen-year-old Golden Girl, from the top of her long, platinum blond hair to the tips of her black and white saddle golf shoes.",
    "Her swing began with a cat-like stretch of the arms, followed by a sway of hips and tilt of left shoulder under her chin.",
    "At the top of her swing, she'd pause before hopping to her left side, the rest of her tightly wound body unfurling like a cat.",
    "Favoring tennis skirts or hot pants, tight tops, hair ribbons to match, she could have passed for a glamourous ice skater performing a clean single toe-loop combination on the fairway.",
    "Maybe she was there to protect her daughter - who was a couple of years younger - from what could have turned into a hair-pulling, nail-scratching cat fight among a gritty pack of girls who had gotten along fine with make-shift swings and down-to-earth looks.",
    "Boys and fathers followed her around the course, cheering her on like fans at a beauty pageant, counting their blessings and her strokes.",
    "There was the clatter of spikes on pavement, the usual nervous silence as we checked in, received official scorecards, instructions, pairings.",
    "That July and August, Sister and I competed in junior tournaments every week, all over Southern California, while our two brothers attended football camp on Catalina Island and hiked the Sierra with other Boy Scouts.",
    "Hole after hole, while we were busy extricating our balls from bad lies and bunkers, throwing our bags down on the ground, shirts untucked, shoes unpolished, haggling over rules, she'd walk down the middle of the fairway unscathed like she was parting the Red Sea, eyes fixed to the flag.",
    "On the greens, we wiped our hands on our shorts, licked our balls clean while Laura polished hers with a small white cloth tucked into the back of her skirt.",
    "To pose, arms high, hips spinning toward the target, blond hair swishing across our shoulders, wrapping the club around our bodies.",
    "After that, Sister broke the house rules - staying out late and riding in Brian Francis' Pontiac - and accepted a gold promise ring by the time she was fourteen.",
    "She went about her business capturing various golf titles, but knew she was fully back in the swing of things after she unseated her hairdresser for the crown of Tahoe Braless Champion.",
    "She'd toss her mane of blond hair back over her shoulders, paw the ground with her golf spikes, and dig in her heels before bracing herself in a sturdy stance.",
    "Sister loved how James kept his cool during his golf match against the gold smuggler in which his opponent's caddie Oddjob started playing dirty, slicing the head off a nearby statue with his flying bowler hat.",
    "She, too, envisioned an exciting, dangerous life with someone like James who would play hard at golf and play hard after.",
    "She also took cues from Pussy Galore, Goldfinger's sidekick and pilot, and developed a persona on the course that said, loud and clear, Don't mess with me.",
    "While I hid in the shadows of Mom's skirts, she was the first one to refuse to follow traditional dress codes for girls over twelve.",
    "She radically protested those wrap-around skirts that billowed or flapped open and made swinging difficult if impossible in a stiff Santa Ana wind.",
    "It was as though her swing was guided by a subterranean force, rising up through the earth into her slim ankles and muscular legs.",
    "Eventually Sister took the reins, unloaded the guns, and headed to the fairways like a woman on a mission: to get the ball into the hole.",
    "It was a little known fact that the elevated par-three fifteenth hole was the best site for checking out legs on Ladies' Day.",
    "Twice a week during summer, Brian Francis and his friends, tipped off by some of the caddies, stationed themselves in the bushes below the tee while groups of women and girls took aim.",
    "She knew he was one of the weirdos spying on her-and that he attended that privileged school, Loyola High - but eventually, she agreed to play golf with him.",
    "Those culottes -t he red ones - were the reason a certain wholesome, dark-haired fifteen-year-old Catholic boy named Brian Francis fell in love with her.",
    "Inevitably, those guys would want to take her to Signal Hill to smooch under the oil derricks, but she wasn't that kind of girl.",
    "If a guy truly wanted to find his way into her heart, he'd have to take his swing out to the course with her for a test drive and then a chocolate malt at Dairy Queen.",
    "If he was a loser, weak in the knees, had poor table or putting manners, cursed, swore, spit or simply failed to outdrive her - she'd cut him loose.",
    "But little Sister, under-aged at thirteen, was routinely being dropped off at the golf course in a Corvette or Camero by a smooth-skinned guy named Roger or Chad, and sometimes a bad boy named Dean.",
    "Worse, if he crossed the line with his affections or advised her to play a shot safely, she'd lead him to the edge of the fairway where she'd give him a good shove out of bounds.",
    "Under the right circumstances, a boy might find himself face down in a grave-sized divot that she'd sculpted with her own sharp-bladed wedge.",
    "She'd brush a direct hit off with a silly ditty like, Little mice think twice, while making giant strides toward the doomed target.",
    "If they didn't past the test, if they couldn't outdrive her with some regularity or keep up with her pace, then they'd know enough to disappear.",
    "She also figured out that all it took to get a guy to wrap a club around a tree or toss it in the lake - knowing he'd have to retrieve it when his parents found out - was to beat him in a match.",
    "I felt unsteady and more nervous than I'd ever felt as I stood, surrounded by high fisherman's nets, on a slice of green Astroturf, ready to hit a ball.",
    "After sticking on a beauty mark and lining her lips in a red angel-pout, she dropped me on Wilshire Boulevard, in the vicinity of Walter Keller's shop.",
    "With my golf shoes and leather glove in my hands, I walked the street, passing cocktail lounges and ancient memorabilia shops, until I reached Walter Keller's Golf Shop.",
    "With a driver in hand and a par-5 looking me long in the eyes, I'd wind up on the backswing until the clubhead wrapped around the side of my head, threatening to knock me from behind.",
    "My friend, Susan Carla, had not only passed her driver's test, but to celebrate the occasion, bought a VW bug so we could drive up to Hollywood to see the hippies on Sunset Boulevard.",
    "Susan Carla - a curvy blond bombshell at sixteen and aspiring actress - wanted to find Schwabs, a coffee shop where Lana Turner had supposedly been discovered.",
    "It wasn't a fancy place and when I spied Mr. Keller - the wizened, kindly man behind the counter - I realized he wasn't a glitzy pro, either.",
    "When she started back down at the ball, it was like watching a line of dominos release in perfect, mesmerizing order.",
    "Amy told me she learned to swing hitting balls off a plastic mat into a net inside a room at Walter Keller's Golf Shop in L.A.",
    "Bob Dylan blared on the radio, and we wailed along, How does it feel/How does it feel/To be on your own/With no direction home/Like a complete unknown/Like a rolling stone.",
    "Maybe I'll just give up trying to be a movie star, Susan Carla said at the next red light, checking her lipstick in the rear-view mirror.",
    "Twelve years old and freckle-faced, she looked right into my fourteen-year-old freckle-face and said, I can make the same swing with my eyes closed.",
    "If you eat ten pieces of white bread soaked in milk every morning, swallow twelve watermelon seeds a day, and kiss a handsome boy goodnight, no one will be able to keep up with you.",
    "If the wind was off-shore, sometimes we'd be lifted off our feet, too - though when Grandpa held it, he was steady as a rock.",
    "But something in our words sounded so ridiculously far from what we hungered for that when we turned to look at each other, we burst out laughing until our sides ached and the car behind us honked to let us know the light had turned green.",
    "Long ago Grandpa and his friends had made a vow to act like little children on the course because that's the only way to enter the kingdom of golf.",
    "Down the fairway, the stories they told: WWI, WWII, Korea...parachuting out of planes ...spies...gunboats ...long-legged nurses...meeting the President...eight months in a submarine...island women...one-star hotels...flying insects big as cigars.",
    "By the fifth hole, I just went along, arriving at the ball, making a swing, it didn't matter where it went, I wanted to get on with it to hear the rest of the story.",
    "They bantered over the length of gimme putts and mulligans, more concerned about retrieving balls from lakes with makeshift poles with assistance from extended arms than getting their scores straight.",
    "He drove a fancy red Cadillac with a special radio he called his ham that could connect him from our house in Long Beach, to Russia, if he wanted to.",
    "Of course, my parents had informed him, but he also had been watching me at the course where, after his regular morning eighteen-hole round with the men, he played rummy in the grill overlooking the tenth tee.",
    "I looked up to see Grandpa in the window, his face registering a smile, mouth opening and closing, arms flapping at his sides, an enormous bald eagle in his argyle vest, cheering me on.",
    "Both Mom and Dad wanted to make little golfers out of us kids, but Mom was especially grateful to have a place where we could run loose and she could get out of the house.",
    "I knew what I had to do - impress them all! They teed off in rapid-fire order, zoomed off in their carts, then remembering that I hadn't hit yet, shifted into reverse and raced back, grinning and apologizing.",
    "I caught sight of the ball as it landed in the fairway, not so very far away, not at all what I'd hoped to convey in that one swing.",
    "He swung the club sideways around his body the same way he'd pitched endless bails of hay while growing up on a farm in Minnesota.",
    "His eyebrows were black and extraordinarily bushy, hanging like two arched caterpillars over his eyes, and yet there wasn't any hair on his head, except for silver patches by his ears, those giant ears that he could wiggle one at a time.",
    "On windy days, he'd drive us grand-kids to the top of Palos Verdes and tie a homemade twenty-five foot butcher-paper, balsa wood kite to the back of his fender.",
    "In the late sixties, Mom and her foursome of ladies used to take off for a weekend of golf in the fall at Gilman Hot Springs.",
    "But every now and then when Mom would pause at the top of her swing just right and the ball would float off her clubface, she'd smile and recall the gift of Maurice.",
    "Taking a fancy to her, he handed her a business card, on the back side of which was handwritten, I have had a certified vasectomy.",
    "It's possible that the golfer's boldness put ideas in her head about to go about ensnaring the charismatic singing golf pro Maurice Jara.",
    "Each spring Maurice played the male lead Alessandro, the ill-fated Indian lover of the beautiful Ramona, in the Ramona Pageant performed in the foothills of Hemet.",
    "The weekend of the Invitational, when Maurice gave a swing demonstration, Dad and the other husbands noticed that the ladies liked looking at Maurice as much as his swing.",
    "At the dinner party in the clubhouse that evening, Maurice danced with the ladies - not too close - which reassured everyone that he was a perfect gentleman.",
    "To Mom and the ladies, this was something they could realistically reach for and a lot more fun than trying to build strength through isometric drills that called for standing in hallway door jambs, pressing muscles against walls.",
    "His pause at the top of the backswing was a lengthy, lingering moment that suggested he'd stay awhile and have one more drink.",
    "It gave you the feeling that he had all the time in the world for you, whether he was changing your grip against a backdrop of prickly pear cactus, red rocks, and palms or singing plaintive Mexican love songs in his deep tenor's voice that made you think of beauty and heartbreak.",
    "Mom and the ladies felt Maurice certainly deserved more than to be teaching in the barren desert or on stage one season each year.",
    "With lightly bronzed skin, soft black hair and aquiline nose, his sweeping, mellifluous backswing and leg action evoked the grace of a Spanish dancer.",
    "Just watching him made you see that the swing wasn't all about muscling the ball like the young pros such as Jack Nicklaus seemed to be doing.",
  ],

  combo: [
    "#long#",
    "#long#",
    "#medium# #short#",
    "#short# #medium#",
    "#short# #short# #short#",
  ],
  origin: ["#combo#"],
});

grammar.addModifiers(tracery.baseEngModifiers);

const getTweet = function () {
  return grammar.flatten("#origin#");
};

module.exports = getTweet;
