const tracery = require("tracery-grammar");

const grammar = tracery.createGrammar({
  short: [
    "Mom's a mood swinger.",
    "In between swinging, Mom did housework.",
    "Part of an heirloom chandelier crashed to the ground.",
    "She swung on top of the bed in my younger Sister's room.",
    "But this was something I confirmed after I had my own swing.",
    "What exactly happened out there?",
    "At some point, I remember yanking on her arm, asking, Why swing?",
    "Swimming builds bulky shoulders and chlorine turns hair green.",
    "I swallowed my pride and listened to Mom: Give yourself time.",
    "She'd shake her head, call after the ball, Dingbat!",
    "Dad didn't mind.",
    "Dad's the original swinger.",
    "Sister and I were wowed.",
    "Sometimes you have to stand up for yourself or you'll get walked on.",
    "Then Mom showed us how it was done.",
    "Sister and I scuttled off, eyes cast down, confused.",
    "Keeping his head down during the swing had new meaning.",
    "By the eighteenth hole, they were jumpy.",
    "Every golf shot sounded like gunfire, and vice-versa.",
    "They'd swing and duck. Hit and run.",
    "But Dad wanted to do it the right way.",
    "He withheld judgment of shots.",
    "I was sure he had it turned around.",
    "I didn't want to work at something that was supposed to be fun.",
    "I'll never forget one of our early outings to the course with her.",
    "One man took a practice swing on the elevated tee directly behind us.",
    "But Mom, all five-foot-three inches of her, wasn't one to back down.",
    "That didn't mean love or life was without challenges, though.",
    "He had one golf lesson in his youth, and maybe a couple more after that.",
    "That Dad could count on this shot with regularity gave him confidence.",
    "Caught in enemy cross-fire, the commander refused to call it quits.",
    "When he returned home, he didn't waste time asking for Mom's hand.",
    "Mom secretly hoped she'd be presented the engagement ring on the course.",
    "He wanted us to see that golf was a game of possibilities.",
    "What amazed me most were the things she could make the ball do.",
    "Well, Dad would pump us up: Swing like you know how.",
    "Dad's brown wingtip spikes made a great clack on the pavement.",
    "Sister and I could barely make out the flag at the end of the hole.",
    "If the shot didn't go as well as we liked, he'd toss us another ball.",
    "As part of the deal, Dad promised to keep Mom on the golf course.",
    "He is everything they say he is, too, she recalled to me.",
    "Hands like horses' hooves.",
    "A guest snapped a photo and sent a copy to her.",
    "I stared at that photo a lot.",
    "At age eight, I didn't know what to think.",
    "Not in a bad way, Mom recalls, smacking her lips.",
    "No, Dad said, he didn't.",
    "But back to her dislike of wrinkled shorts.",
    "A good swing doesn't need flaunting, Mom said.",
    "And she sternly advised Dad, Look but don't touch.",
    "A gentleman doesn't think with his muscles.",
    "Then she'd step outside of her car to zip them up.",
    "Keep your thighs firm on the downswing.",
    "The locker–room attendants spied on her with binoculars.",
    "Afterwards, he patted her on the back for well–done leg action.",
    "However, this proved to be an ideal arrangement for both.",
    "While caddies called her Fanny, golfers tagged her End Joys.",
    "Wives didn't trust her and snubbed her on the course, but not Mom.",
  ],
  medium: [
    "Mom, pressed cheek to cheek and in the arms of a man who wasn't my father?",
    "Mom and Dad hung it proudly on the hallway wall along with our other family photos.",
    "It was well known that she didn't believe in wearing underwear, either.",
    "Was there a skirmish? Did my dad protest, maybe throw him a punch?",
    "They both agreed, however, that she'd been endowed with true swing talent.",
    "End Joys had already been through several husbands before taking up golf.",
    "Between songs, when Dad went off to get Mom a cold drink, Arnold moved in.",
    "One of the most masculine men, with or without a swing, she's ever met.",
    "The weeks following, much to Mom's delight, Dad started swinging from his heels like Arnold.",
    "Mom was giddy with excitement. Then, for the most part, she became herself again.",
    "Every time I heard the story of End Joys, it grew to voluptuous proportions.",
    "Or that one had anything to do with the other until I accompanied Mom to a lesson.",
    "Set up to the ball with your hindquarters nice and high, the pro told her.",
    "It was on the back nine of a hilly course in northern China that the shooting began.",
    "My brothers skipped alongside, their hands spilling over with soda and candy.",
    "He motioned us over to a ledge of grass. Below that, the world grew bigger and greener.",
    "On the first tee, in my shorts, cotton blouse, and tennis shoes, I squinted into the sun.",
    "From the start, Dad's family plan was to give us four kids a positive spin on golf.",
    "Aunt Margaret believed that I would find the best swing in my own shadow.",
    "Facing the dresser mirror, she could view the entire swing in that mirror.",
    "We're going out to play, they'd holler at us four kids and the babysitter.",
    "After that day, not only did I crave Mom's swing, but I wanted Dad's power.",
    "Then he gripped a wood club, gathered himself up like a bear and lashed out.",
    "I spooked at the cracking sound, thinking it was my head that shattered.",
    "Nevertheless, I couldn't ignore his tactics because they seemed to work.",
    "Once we understood this, he felt sure we'd make our way through life just fine.",
    "With his dead-eye aim, he taught us how to line up putts and read breaks in greens.",
    "She also didn't like that boys talked to her chest or assumed that they ruled the world.",
    "Your swing will not fail you, he'd say. Only your thoughts will— if you let them.",
    "A foursome of men arrived on the first tee just as Sister and I were preparing to hit our drives.",
    "He reminded us, Never let fear rule your decisions. Even if the ball was tangled up in roots.",
    "She'd given up on making her mark on the high school hockey field or tennis courts.",
    "From that day on, until Betty left, she didn't want to give him the idea that she was a pushover.",
    "This intrigued me to no end, the idea that the club was alive with power——even over Mom.",
    "Then, off they'd go, bumping through the kitchen door, bags of clubs rattling across their backs.",
    "She could sling a 7-iron past her hips faster than Dad could fling burgers onto the barbeque.",
    "What women were swinging back then, in the early sixties, other than Mom and Aunt Margaret?",
    "Life isn't as simple as you think, she explained to us, her rebel accomplices.",
    "I knew she was trying to teach me something big and wonderful, but I wasn't so sure.",
    "She quickly squelched our quarrels with alluring buckets of shiny, white balls.",
    "One night Mom got carried away and miscalculated the height of her backswing.",
    "If he ever tried to take that away from her, she quite possibly would kill him.",
    "You know what it's like to stand on the first tee? Jitters, hopes, expectations.",
    "She'd swing, the ball would fly high, low, slice to the right or hook to the left.",
    "Walking and swinging, shot after shot, she'd advance the ball toward a distant red flag.",
    "There was a bench on the par-3 seventh hole where they liked to hold hands and talk.",
    "At the dinner table, when we kids asked where he got his power from, Mom pointed to his stomach.",
    "Dad could see soldiers in the trees aiming rifles at them from a fifty-yard pitch shot away.",
    "He was a twenty-three year old ensign assigned to a heavy cruiser stationed in the China Seas.",
    "The commander knew Dad was a low-handicap golfer, and ordered him to bring his clubs along.",
    "After a week, Mom, resolving to finish, dragged her bag along the final hole in near exhaustion.",
    "Ever the straight-shooter, she placed her ball carefully on the tee as though lighting a fuse.",
    "Dad handed each of us a club and ball, and told us, All you want to do is have a good time today.",
  ],
  long: [
    "By age fourteen she'd grown to hate her too short, too-freckled, too-bosomy, too far-sighted, too-bookish, too red-headed self.",
    "Taller, leggier girls seemed to have the advantage of both speed and strength, which only fueled her competitive fever and made her feel as though she was missing out.",
    "Borrowing her Dad's whippy-stick golf clubs, she sought refuge at the course across the street from her house in Long Beach.",
    "Though she had little idea of the swing, she discovered that a metal-headed club could be used as an ax or wand.",
    "It thrilled her to attack the ball, to spin her body up into a bee-hive of power and emotion and then let loose with a sting, zinging like a slap across a lecherous boy's face.",
    "Other times she found that a lighter touch, something most of the boys she'd observed couldn't bring themselves to try, worked like magic, especially around the greens.",
    "Before long, she noticed that a well struck shot commanded attention and respect, and for someone as small and unsure as she, that was a big deal.",
    "Mom's hopes for becoming an accomplished golfer blossomed the day she saw Betty Hicks swinging across the fairways with power and ease.",
    "It turned out that Betty was even shorter than Mom, but in a good Santa Ana wind, her ball could carry twice as far.",
    "As a kid, I thought I knew everything about Mom until I discovered her habit of swinging: on the lawn, living room, bedrooms, hallway, bathroom, and kitchen.",
    "Other than a club, she'd use a rake, a broom, a stick, a spatula, a baseball bat——whatever she could grip her hands on.",
    "She'd strike at plastic Wiffle balls, lemons, avocados, magnolia seeds, Ping-Pong balls, the dog's old tennis balls, Dad's wadded up socks, just about anything that would fall from a tree or land at her feet.",
    "Over the flap of wet clothes tossing in the dryer, I could make out the repetitive sound of our lawn being gutted, piece by piece, or of a vase shattering from an overzealous swing.",
    "I'd hear the roar of the upright Hoover approaching my bedroom door, knowing she was grooving a smooth path to an electric putting machine.",
    "She'd make a great whipping, swishing noise with a club that could shake a lamp, unfurl curtains, or rattle a tree.",
    "Swinging in front of her full-sized bedroom mirror, wearing only a lacy Maidenform bra and silk half-slip, she'd set off a trail of sparks on the green shag carpet and around her stockinged feet.",
    "The swing made her white skin hot with color, and her red hair would tumble from its French twist, bobby pins falling to the floor.",
    "She didn't get worked up. She just gathered the pieces and laid them on the table to glue together later on.",
    "What amazed me was the possibility that she might not know what her swing was doing at all times. As if it had a mind of its own.",
    "Sunday was the one day of the week Dad didn't go to the law office, and Mom wasn't running off to a community meeting.",
    "After church, they couldn't wait to shed their dark church clothes for matching sporty outfits in bold tropical and plaid prints.",
    "They'd return at sunset, their cheeks sun-kissed, hair wind-blown, grass cuttings on their legs, shirts untucked, laughing like kids.",
    "It was a mystery to me what they did with those clubs for four hours at a time while I played kick-ball with my friends.",
    "Though my green-eyed Mom looked incredibly agile and loose-limbed swinging a club around the house, her skill seemed to me no more useful than baton twirling and having nothing at all to do with the sweat and punch of real sport.",
    "As far as I knew, not my best friend's mom, not my second grade teacher, not Barbie Doll, not Jackie Kennedy, not Joan Baez, not the Supremes, not Jane Fonda.",
    "I'm doing what few women do, Mom told me. To her, golf was the next best thing to climbing Mt. Everest.",
    "Nevertheless, she heartily defended golf by pointing out the drawbacks of more popular sports: Horseback riding broadens the haunches, skiing overworks the thighs and wind-burn parches the skin.",
    "Tennis jars the joints and face muscles—though she herself was very accomplished at all of these sports and had prize ribbons and a leather riding crop to prove it.",
    "Mom made the swing look so easy that I figured it was something that could be handed off to me like a birthday present or could be caught like a cold or would fall into my hands through a crack in the universe.",
    "However, when she showed me how to grip a club and swing—and I missed the ball entirely—I wanted to quit.",
    "So I turned to some of our golfing relatives hoping they could tell me the quickest way to a swing.",
    "The advice I got was daunting to me, a strawberry-haired girl in cut-offs and rubber flip-flops with a big dose of impatience.",
    "Grandpa Wallace told me that I should try to swing the head of the club like a gong so that it would strike me in the head at the start and the finish.",
    "Uncle Bill said that it was essential to swing with my ears plugged and he offered cotton balls.",
    "During long summer days, armed with clubs she called weapons, Mom began taking us to the course near our home in Long Beach.",
    "We'd hit with abandon, running up and down the fairways and hills, sometimes on one leg or with one hand, balls flying forwards or backwards, it didn't matter.",
    "Feeling like little savages, we'd take off our tennis shoes to grip the cool grass with our toes.",
    "My brother Don, hipless as a snake, held his pants up with one hand and dragged an old set of Dad's clubs behind him with the other.",
    "Alex, the eldest, slumped to the grass and cried whenever he lost a favorite ball to a lake or the bushes.",
    "Sister and I got poked in the chin swinging clubs that were too long. We tired easily in the hot sun.",
    "I soon learned that the game wasn't always easy for Mom like I'd thought. Certain shots rubbed her wrong.",
    "Especially worm burners—balls that rolled on the ground—or fliers that sent her into the woods and drained color from her face.",
    "If she strung more than five dingbats in a row, we could count on eating frozen peas and fish sticks for dinner instead of roast.",
    "However, later in the evening she'd usually be at it again, swinging under floodlights in the backyard.",
    "No matter where the balls flew, Dad——ever a team player——would applaud her from his vantage at the end of the garden where he'd stand with a club in his hands, dislodging Wiffle balls, like ripe fruit, from the trees.",
    "Renewed, Mom would return to the kitchen to dish out bowls of rocky road ice cream for each of us.",
    "She'd take a stance in the mud or from behind a prickly tree, or toss a pinch of grass in the air, or get down on her hands and knees to sight a line—just to get the ball closer to the hole.",
    "On the greens, whenever she sunk a long putt, she'd prance on her toes while retrieving the ball—her hair, piled in wide equally spaced curls on top of her head, bouncing like a coiled Slinky.",
    "Mom's gutsy attitude landed her in the heart of controversy, whether running PTA meetings or staking a claim on the course.",
    "Then, as if we were invisible, he set up to the ball and aimed his shiny metal-shafted club right over our pig-tailed heads.",
    "But then we saw Mom's size-five white golf shoes moving quickly toward him, her flowered Lilly skirt fluttering around her knees as she marched up the bluff.",
    "She caught his attention with a brisk wave of her pink gloved left hand and in her most reasonable voice, delivered her message, Gentlemen, this is our starting time!",
    "Those men looked ominous standing there with their clubs and big leather golf bags, grumbling in voices deep and gruff.",
    "She put her hands on her hips and said something I couldn't hear, and before I knew it, they were nodding their heads and stepping aside.",
    "She flexed her knees and made a mighty swing that wrapped the club around her shoulders, smacking the ball good and hard, like she was splitting the fairway wide open for us.",
    "He'd go along quite agreeably with each pro's suggestions, but afterwards would go right back to his true blue swing.",
    "Tall, athletic, and barrel-chested, he'd hover over the ball in a wide stance, with lowered right shoulder as if bracing for a strong wind.",
    "He'd cock his head one more time to check his aim which was always extreme left—the next fairway over.",
    "Then summoning concentration, he'd make a grand upright sweep of the club and bring it back to the ball with a driving punch of wrist and arms.",
    "The resulting shot would be a banana ball to the right that no one, except Mom, ever believed would make that sharp turn in time to find the fairway.",
    "He befuddled fierce competitors who'd throw adolescent tantrums when their groomed swings sent balls wayward into the woods or duck pond.",
    "Over the years, a lot of people, including myself, tried to convince him to aim straight. He'd gently nod toward his ball lying in the middle of the fairway.",
    "Dad played golf during high school at Long Beach Poly and that's when he met Mom. Roaming the neighborhood golf course, his eyes were drawn to her swing and vibrant red hair.",
    "Whenever he strayed from his foursome of spitting, cursing teenage boys, she'd timidly drop her clubs and scale the nearest tree to get away.",
    "Undeterred, he'd throw rocks at her feet until she'd agree to climb down and play a few holes with him.",
    "According to Mom, she—a tiny thing to his six foot three—kicked my father good and hard and often to let him know, in no uncertain terms, that if he wanted her, he must defer to her number one love—golf.",
    "Her passion enamored Dad. By the time he went off to Annapolis, he'd decided that she, the sixteen-year-old sportswoman, would make a terrific wife and mother.",
    "At Annapolis he competed in lacrosse, football, Ping-Pong, and boxing——playing golf in his spare time.",
    "That's when he took a bit of knowledge and technique from each of those sports and parlayed them into his golf swing.",
    "He knew that a strong right cross to a boxing foe's ear could knock him out, and that the same principle translated to a golf swing would make a big impact on the ball.",
    "In boxing, too, he learned to be light and quick on his feet, and took that dance into his golf swing.",
    "He called upon the wrist action of a back-spin serve in Ping-Pong whenever he wanted a golf ball to bite or stop on the green.",
    "By the time the navy sent him to China in 1947, he'd settled comfortably into a one woman-one swing theory.",
    "My mom hadn't agreed to marry him yet, and the fact that he was a golfer almost got him killed while on duty.",
    "He'd heard that there were challenging courses in China, which he hoped he could play before Comrade Mao got a hold of the country.",
    "Within weeks, the political situation grew tense with the communists battling Chiang Kai-Shek's forces.",
    "Even so, the commander ordered Dad, the assistant medical officer, and another shipmate to shore for a game.",
    "They also were dropping mortar shells from the hillside into the rough, persuading the golfers to avoid hunting down errant balls.",
    "But the commander assured him that the soldiers were just firing at the ground and over their heads to scare them.",
    "That day, Dad gained a key insight to lifetime enjoyment of the game: Standing over anything too long isn't healthy.",
    "In Mom's parent's house, Dad made his good intentions known to his future father-in-law who sat, nodding his head in a silk smoking jacket.",
    "They spent their August honeymoon in San Diego, each day playing tennis in the morning, followed by 36 holes of golf.",
    "The summer of '60, before I turned eight, he drove us in his Chevy wagon through our tidy Long Beach neighborhood of cement sidewalks and shuttered stucco houses.",
    "He turned down a shady street of oleanders and eucalyptus where the road narrowed between the two flagstone pillars that marked the golf course.",
    "Parking next to the Spanish style clubhouse, with its white-washed walls and red-tile roof, he and my brothers, Alex and Don, took off toward the pro shop to fetch a brown leather pull cart for Mom and a canvas carry bag for himself.",
    "Sister and I followed Mom into the ladies' locker room where she kept her golf shoes, Swiss Army Knife, Doublemint Gum, Saltine Crackers, Vienna Sausages, a pair of beige stockings—necessities.",
    "Mom's finger traced a speck of a white ball in blue sky until a magical cloak of green rose up to swallow it.",
    "As if we needed convincing Dad rose from the table so we could take turns hammering away at his round but firm belly.",
    "But Dad soon proved that strategy, more than strength or a perfect swing, was the best way to get around a course.",
    "He knew about percentage shots—when to hit right through a tree, to aim for the flag stick, or hold back.",
    "A ball that rolled on the ground was no less than one that flew in the air—they both had a chance to put you closer to the hole.",
    "Most of all over that first summer on the course, Dad wanted us to realize that the world wasn't going to end with one miss-hit.",
    "Arnold Palmer eyed Mom as she trotted by him at the crowded cocktail party during pre-tournament festivities for the Bob Hope Desert Classic tournament.",
    "Dad was there too——they were last minute guests of someone who knew Someone.",
    "This was during the days of martinis, frosted pink ice lipstick, Zippo lighters, plastic bauble beads, and men's gold rope chains (peering out from their partially unbuttoned, pointy collared polyester shirts).",
    "Mom wore a pink knit dress, cinched at the waist with a wide gold belt and gold hoop earrings.",
    "She was dancing up a storm that night to Frank Sinatra tunes with Dad, who, never one for polyester and chains, preferred to charm her with masterful footwork that kept her on her toes.",
    "Dad didn't mind Arnold swing dancing so close to Mom in the shimmering night, saying, I was the real winner that night. I got to go home with the prize–your mom.",
    "Tan and dazzlingly handsome in dark suit, white shirt, and tie, he stepped up behind her like a prizefighter and wrapped his burly forearms around her waist.",
    "When the music started, he danced like he swung, from his heels hard and steady, twirling Mom with his powerful right arm, thundering and crashing through the crowds to clear the way for this queen of the night.",
    "Before releasing her back to Dad, Arnold told her that she was the most ravishing redhead in the room.",
    "Only later did I understand that when all the pieces flowed together, it was called good timing.",
    "She was a woman at the course who Dad recalled once or twice as being loads of fun to watch, and Mom described as no one's mother.",
    "She apparently found her true sport in golf, and practiced long hours on the putting green and range.",
    "She had a white streak in her coffee–black bouffant hair, and wore tight bermudas and see–through blouses.",
    "End Joys would drive to the course with her shorts unzipped so she would look freshly pressed.",
    "She felt it interfered with her swing; she claimed that she was allergic to the elastic in bras and panties.",
    "To get an idea of how far she'd go, she refused to ride in the golf cart with her latest husband, an insurance agent. Instead, she'd walk ahead of him.",
    "There'd she be, every afternoon, on the practice green, bending over to line up putts, or taking a wide stance on the range, under the watchful eyes of a pro, polishing her pre–swing waggle—a sassy wiggle of her extraordinary heart–shaped rear.",
    "When men passed by, they'd croon to each other, If this is my dying day, then please, lord, let her be my End Joys.",
    "Mom appreciated a good swing (though the few times we saw End Joys, Mom forbade Sister and me to grow up looking like her).",
    "Before hearing of End Joys I didn't know that people were thought of in sections like fryer chickens–arms, legs, thighs, hips, hindquarters, breasts.",
    "Or that the golf swing was likewise broken down into parts—grip, set–up, backswing, downswing, follow–through.",
  ],
  combo: ["#long#", "#long#", "#long#", "#medium# #short#", "#short# #medium#"],
  origin: ["#combo#"],
});

grammar.addModifiers(tracery.baseEngModifiers);

const getTweet = function () {
  return grammar.flatten("#origin#");
};

module.exports = getTweet;
